#!/usr/bin/env bash
# Publish the recalibration map to GitHub Pages, only when run explicitly.
#
# The map is a generated artifact (ignored in git). This script writes it to an
# orphan `gh-pages` branch as a single commit and force-pushes that branch, so
# ordinary pushes to `main` never republish and the branch never accumulates
# history. Pages serves the branch root: https://janb1989.github.io/EU5WorldBuilder/
#
# Usage: scripts/publish_map.sh            (publishes artifacts/recalibration_map/index.html)
#        scripts/publish_map.sh --rebuild  (runs `worldbuilder recalibration-map` first)
set -euo pipefail
cd "$(dirname "$0")/.."
if [[ "${1:-}" == "--rebuild" ]]; then uv run worldbuilder recalibration-map; fi
src=artifacts/recalibration_map/index.html
[[ -f "$src" ]] || { echo "missing $src; run: uv run worldbuilder recalibration-map" >&2; exit 1; }
remote=$(git remote get-url origin)
stamp=$(date -u +%Y-%m-%dT%H:%MZ)
head=$(git rev-parse --short HEAD)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/site"
cp "$src" "$tmp/site/index.html"
cp artifacts/recalibration_map/map_manifest.json "$tmp/site/map_manifest.json"
touch "$tmp/site/.nojekyll"
cat > "$tmp/site/README.md" <<EOF
# EU5 World Builder — recalibration map
Published $stamp from commit $head. Generated by \`scripts/publish_map.sh\`; not rebuilt on push.
EOF
git -C "$tmp/site" init -q -b gh-pages
git -C "$tmp/site" -c user.name="$(git config user.name)" -c user.email="$(git config user.email)" add -A
git -C "$tmp/site" -c user.name="$(git config user.name)" -c user.email="$(git config user.email)" commit -q -m "Publish recalibration map ($stamp, source $head)"
git -C "$tmp/site" push -q --force "$remote" gh-pages:gh-pages
echo "published $src ($(du -h "$src" | cut -f1)) from $head -> gh-pages"
echo "https://janb1989.github.io/EU5WorldBuilder/"
